apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.licenseServer.service.name }}

spec:
  selector: {}
  ports:
    - protocol: TCP
      port: {{ .Values.licenseServer.service.port }}
      targetPort: {{ .Values.licenseServer.port }}
      name: {{ .Values.licenseServer.service.name }}
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Values.licenseServer.service.name }}
  labels:
    component: license-endpoint
subsets:
  - addresses:
    -
      ip: {{ .Values.licenseServer.ip }}
    ports:
      -
        port: {{ .Values.licenseServer.port }}
        name: {{ .Values.licenseServer.service.name }}