licenseServer:
  ip: "REQUIRED"
external:
  host: 192.168.49.2
secret:
  base64dockerconfigjson: "REQUIRED"
docker:
  registry: "REQUIRED"
  nameSeparator: ":"
  versionSeparator: "-"
  versions:
    base: 23.4.0-SNAPSHOT
    api: 23.4.0-SNAPSHOT
    datasets: 23.4.0-SNAPSHOT
    analysis: 23.4.0-SNAPSHOT
    lemaData: 23.4.0-SNAPSHOT
    lema: 23.4.0-SNAPSHOT

entity:
  storage:
    maxHeapSize: 500M
    heapNewSize: 100M
filestore:
  dataVolumeSize: 10Gi
analysis:
  concurrency:
    face: 2
    vehicle: 2
    object: 2
datasets:
  locations:
    replicas: 1
lemaUi:
  replicas: 1
