apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.api.config }}
data:
  SPRING_PROFILES_ACTIVE: "lema"
  ISOL_ENTITY_STORAGEDB_HOST: "{{ .Values.entity.storage.service.name }}"
  ISOL_ENTITY_STORAGEDB_PORT: "{{ .Values.entity.storage.service.port }}"
  ISOL_ENTITY_INDEXDB_HOST: "{{ .Values.entity.index.service.name }}"
  ISOL_ENTITY_INDEXDB_ACI_PORT: "{{ .Values.entity.index.service.queryPort }}"
  ISOL_ENTITY_INDEXDB_INDEX_PORT: "{{ .Values.entity.index.service.indexPort }}"
  ISOL_AUTH_SERVICE_PROTOCOL: "{{ .Values.auth.service.protocol }}"
  ISOL_AUTH_SERVICE_HOST: "{{ .Values.auth.service.name }}"
  ISOL_AUTH_SERVICE_PORT: "{{ .Values.auth.service.port }}"
  ISOL_AUTH_SERVICE_PATH: "{{ .Values.auth.service.path }}"
  ISOL_AUTH_SERVICE_EXTERNAL_PROTOCOL: "{{ .Values.external.protocol }}"
  ISOL_AUTH_SERVICE_EXTERNAL_HOST: "{{ .Values.external.host }}"
  ISOL_AUTH_SERVICE_EXTERNAL_PORT: "{{ .Values.external.port }}"
  ISOL_AUTH_SERVICE_EXTERNAL_PATH: "{{ .Values.auth.external.path }}"
  ISOL_AUTH_SERVICE_REALM: "{{ .Values.auth.realm }}"
  ISOL_AUTH_SERVICE_API_CLIENT: "{{ .Values.auth.apiClient }}"

  ISOL_FILE_STORE_PROTOCOL: "{{ .Values.filestore.service.protocol }}"
  ISOL_FILE_STORE_HOST: "{{ .Values.filestore.service.name }}"
  ISOL_FILE_STORE_PORT: "{{ .Values.filestore.service.port }}"
  ISOL_FILE_STORE_PATH: "{{ .Values.filestore.service.path }}"
  ISOL_FILE_STORE_BUCKET: "{{ .Values.filestore.bucket }}"

  ISOL_DATASETS_LOCATIONS_DB_HOST: "{{ .Values.datasets.locations.service.name }}"
  ISOL_DATASETS_LOCATIONS_DB_ACI_PORT: "{{ .Values.datasets.locations.service.queryPort }}"

  ISOL_ANALYSIS_HOST: "{{ .Values.analysis.service.name }}"
  ISOL_ANALYSIS_API_PORT: "{{ .Values.analysis.service.port }}"
  ISOL_ANALYSIS_API_PATH: "{{ .Values.analysis.service.path }}"
  ISOL_ANALYSIS_JOBS_PORT: "{{ .Values.analysis.service.jobsPort }}"
  ISOL_ANALYSIS_JOBS_PATH: "{{ .Values.analysis.service.jobsPath }}"

  ISOL_AUDIT_HOST: "{{ .Values.audit.service.name }}"
  ISOL_AUDIT_PORT: "{{ .Values.audit.service.port }}"
  ISOL_AUDIT_DATABASE_NAME: "{{ .Values.audit.database }}"
  ISOL_API_SERVICE_APPLICATION_TYPE: "lema"
  ISOL_API_SERVICE_ALLOWED_ORIGINS:  "{{ .Values.external.protocol }}://{{ .Values.external.host }}"
  ISOL_API_SERVICE_BASE_URL: "{{ .Values.external.protocol }}://{{ .Values.external.host }}:{{ .Values.external.port }}{{ .Values.api.external.path }}"

  ISOL_WATCHLIST_MIN_EVENT_AGE_SECONDS: "60"
  ISOL_STATS_MIN_ANALYSIS_JOB_EVENT_AGE_SECONDS: "60"
  ISOL_API_SERVICE_INTERNAL_PORT: "{{ .Values.api.internalPort }}"
  ISOL_ENTITY_EXPIRY_POLE_LIFETIME_DAYS: "{{ .Values.api.expiry.poleLifetime }}"
  ISOL_ENTITY_EXPIRY_CASE_LIFETIME_DAYS: "{{ .Values.api.expiry.caseLifetime }}"
  ISOL_ENTITY_MAX_MAX_RESULTS: "{{ .Values.api.maxResults.max }}"
  ISOL_ENTITY_DEFAULT_MAX_RESULTS: "{{ .Values.api.maxResults.default }}"
  ISOL_ENTITY_DEFAULT_MAX_SUGGEST_RESULTS: "{{ .Values.api.maxResults.suggest }}"

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.api.secret }}
data:
  ISOL_AUTH_SERVICE_API_CLIENT_SECRET: "{{ .Values.auth.apiClientSecret | b64enc }}"
  ISOL_FILE_STORE_USER: "{{ .Values.filestore.username | b64enc }}"
  ISOL_FILE_STORE_PASSWORD: "{{ .Values.filestore.password | b64enc }}"
  ISOL_AUDIT_USERNAME: "{{ .Values.audit.username | b64enc }}"
  ISOL_AUDIT_PASSWORD: "{{ .Values.audit.password | b64enc }}"
