apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.auth.db.config }}
data:
  POSTGRES_USER: "{{ .Values.auth.db.username }}"
  POSTGRES_PASSWORD: "{{ .Values.auth.db.password }}"
  POSTGRES_DB: "{{ .Values.auth.db.database }}"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.auth.config }}
data:
  KEYCLOAK_DATABASE_HOST: "localhost"
  KEYCLOAK_DATABASE_SCHEMA: "public"
  {{- if eq .Values.external.protocol "http" }}
  KC_HOSTNAME_STRICT_HTTPS: "false"
  {{- end}}
  KC_HOSTNAME: "{{ .Values.external.host }}"
  KC_HOSTNAME_PORT: "{{ .Values.external.port }}"
  KC_HTTP_RELATIVE_PATH: "/{{ .Values.auth.service.path }}"

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.secret }}
data:
  KEYCLOAK_ADMIN_USER: "{{ .Values.auth.adminUser | b64enc }}"
  KEYCLOAK_ADMIN_PASSWORD: "{{ .Values.auth.adminPassword | b64enc }}"
  KEYCLOAK_DATABASE_USER: "{{ .Values.auth.db.username | b64enc }}"
  KEYCLOAK_DATABASE_PASSWORD: "{{ .Values.auth.db.password | b64enc }}"
  KEYCLOAK_DATABASE_NAME: "{{ .Values.auth.db.database | b64enc }}"
