apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.datasets.locations.config }}
data:
  ISOL_LICENSE_SERVER_HOST: "{{ .Values.licenseServer.service.name}}"
  ISOL_LICENSE_SERVER_PORT: "{{ .Values.licenseServer.service.port }}"
