apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.entity.storage.dataVolumeClaim }}
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
    - ReadOnlyMany
  resources:
    requests:
      storage: {{ .Values.entity.storage.dataVolumeSize }}

