apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.api.config }}
data:
  ISOL_SECURITY_DATA_VOLUME_PATH: "/data/security"

  ISOL_ENTITY_STORAGEDB_HOST: "{{ .Values.entity.storage.service.name }}"
  ISOL_ENTITY_STORAGEDB_PORT: "{{ .Values.entity.storage.service.port }}"
  ISOL_ENTITY_INDEXDB_PROTOCOL: "{{ .Values.entity.index.service.protocol }}"
  ISOL_ENTITY_INDEXDB_HOST: "{{ .Values.entity.index.service.name }}"
  ISOL_ENTITY_INDEXDB_ACI_PORT: "{{ .Values.entity.index.service.queryPort }}"
  ISOL_ENTITY_INDEXDB_INDEX_PORT: "{{ .Values.entity.index.service.indexPort }}"
  ISOL_ENTITY_INDEXDB_COMMUNITY_PROTOCOL: "{{ .Values.entity.index.community.protocol }}"
  ISOL_ENTITY_INDEXDB_COMMUNITY_HOST: "{{ .Values.entity.index.community.host }}"
  ISOL_ENTITY_INDEXDB_COMMUNITY_ACI_PORT: "{{ .Values.entity.index.community.aciPort }}"

  ISOL_AUTH_SERVICE_PROTOCOL: "{{ .Values.auth.service.protocol }}"
  ISOL_AUTH_SERVICE_HOST: "{{ .Values.auth.service.name }}"
  ISOL_AUTH_SERVICE_PORT: "{{ .Values.auth.service.port }}"
  ISOL_AUTH_SERVICE_PATH: "{{ .Values.auth.service.path }}"
  ISOL_AUTH_SERVICE_EXTERNAL_PROTOCOL: "{{ .Values.external.protocol }}"
  ISOL_AUTH_SERVICE_EXTERNAL_HOST: "{{ .Values.external.host }}"
  ISOL_AUTH_SERVICE_EXTERNAL_PORT: "{{ .Values.external.port }}"
  ISOL_AUTH_SERVICE_EXTERNAL_PATH: "{{ .Values.auth.external.path }}"
  ISOL_AUTH_SERVICE_REALM: "{{ .Values.auth.realm }}"
  ISOL_AUTH_SERVICE_API_CLIENT: "{{ .Values.auth.apiClient }}"
  ISOL_AUTH_SERVICE_API_URL: "{{ .Values.external.protocol }}://{{ .Values.external.host }}:{{ .Values.external.port }}{{ .Values.auth.external.path }}"
  ISOL_AUTH_SERVICE_UI_CLIENT: "{{ .Values.auth.uiClient }}"
  ISOL_AUTH_SERVICE_UI_URL: "{{ .Values.external.protocol }}://{{ .Values.external.host }}{{ .Values.discoverUi.external.path }}*"
  ISOL_AUTH_SERVICE_TOKEN_EXPIRY_TIME: "{{ .Values.auth.tokenExpiryTimeSeconds }}"
  ISOL_AUTH_SERVICE_BASE_REALM_ROLES: "{{ .Values.auth.baseRealmRoles }}"

  ISOL_FILE_STORE_PROTOCOL: "{{ .Values.filestore.service.protocol }}"
  ISOL_FILE_STORE_HOST: "{{ .Values.filestore.service.name }}"
  ISOL_FILE_STORE_PORT: "{{ .Values.filestore.service.port }}"
  ISOL_FILE_STORE_PATH: "{{ .Values.filestore.service.path }}"
  ISOL_FILE_STORE_BUCKET: "{{ .Values.filestore.bucket }}"

  ISOL_DATASETS_LOCATIONS_DB_HOST: "{{ .Values.datasets.locations.service.name }}"
  ISOL_DATASETS_LOCATIONS_DB_ACI_PORT: "{{ .Values.datasets.locations.service.queryPort }}"

  ISOL_ANALYSIS_HOST: "{{ .Values.analysis.service.name }}"
  ISOL_ANALYSIS_API_PORT: "{{ .Values.analysis.service.port }}"
  ISOL_ANALYSIS_API_PATH: "{{ .Values.analysis.service.path }}"
  ISOL_ANALYSIS_JOBS_PORT: "{{ .Values.analysis.service.jobsPort }}"
  ISOL_ANALYSIS_JOBS_PATH: "{{ .Values.analysis.service.jobsPath }}"

  ISOL_AUDIT_HOST: "{{ .Values.audit.service.name }}"
  ISOL_AUDIT_PORT: "{{ .Values.audit.service.port }}"
  ISOL_AUDIT_DATABASE_NAME: "{{ .Values.audit.database }}"

  ISOL_API_SERVICE_APPLICATION_TYPE: "{{ .Values.api.applicationType }}"
  ISOL_API_SERVICE_ALLOWED_ORIGINS:  "{{ .Values.external.protocol }}://{{ .Values.external.host }}"
  ISOL_API_SERVICE_BASE_URL: "{{ .Values.external.protocol }}://{{ .Values.external.host }}:{{ .Values.external.port }}{{ .Values.api.external.path }}"
  ISOL_API_SERVICE_API_ENABLED: "{{ .Values.api.apiEnabled }}"
  ISOL_API_SERVICE_INIT_ENABLED: "{{ .Values.api.initEnabled }}"
  ISOL_API_SERVICE_SCHEDULE_ENABLED: "{{ .Values.api.scheduleEnabled }}"

  ISOL_WATCHLIST_MIN_EVENT_AGE_SECONDS: "{{ .Values.api.watchlists.minEventAgeSeconds }}"
  ISOL_STATS_MIN_ANALYSIS_JOB_EVENT_AGE_SECONDS: "{{ .Values.api.stats.minAnalysisJobAgeSeconds }}"
  ISOL_API_SERVICE_INTERNAL_PORT: "{{ .Values.api.internalPort }}"
  ISOL_ENTITY_EXPIRY_POLE_LIFETIME_DAYS: "{{ .Values.api.expiry.poleLifetimeDays }}"
  ISOL_ENTITY_EXPIRY_CASE_LIFETIME_DAYS: "{{ .Values.api.expiry.caseLifetimeDays }}"
  ISOL_ENTITY_MAX_MAX_RESULTS: "{{ .Values.api.maxResults.max }}"
  ISOL_ENTITY_DEFAULT_MAX_RESULTS: "{{ .Values.api.maxResults.default }}"
  ISOL_ENTITY_DEFAULT_MAX_SUGGEST_RESULTS: "{{ .Values.api.maxResults.suggestDefault }}"
  ISOL_ENTITY_IDOL_SECURITY_MODE: "{{ .Values.api.idolSecurity.mode }}"
  ISOL_API_SERVICE_API_LOG_LEVEL: "{{ .Values.api.logging.apiLogLevel }}"
  ISOL_API_SERVICE_AUDIT_LOG_LEVEL: "{{ .Values.api.logging.auditLogLevel }}"

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.api.secret }}
data:
  ISOL_AUTH_SERVICE_API_CLIENT_SECRET: "{{ .Values.auth.apiClientSecret | b64enc }}"
  ISOL_AUTH_SERVICE_ADMIN_USER: "{{ .Values.auth.adminUser | b64enc }}"
  ISOL_AUTH_SERVICE_ADMIN_PASS: "{{ .Values.auth.adminPassword | b64enc }}"
  ISOL_INIT_AUTH_ADMIN_USERNAME: "{{  .Values.auth.createAdminUsername | b64enc }}"
  ISOL_INIT_AUTH_ADMIN_PASSWORD: "{{  .Values.auth.createAdminPassword | b64enc }}"
  ISOL_FILE_STORE_USER: "{{ .Values.filestore.username | b64enc }}"
  ISOL_FILE_STORE_PASSWORD: "{{ .Values.filestore.password | b64enc }}"
  ISOL_AUDIT_USERNAME: "{{ .Values.audit.username | b64enc }}"
  ISOL_AUDIT_PASSWORD: "{{ .Values.audit.password | b64enc }}"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.api.filesConfig.configName }}
data:
  entitySchema: |-
{{ .Files.Get "entity-schema.yaml" | indent 4 }}
