apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.initTool.config }}
data:
  ISOL_AUTH_SERVICE_PROTOCOL: "{{ .Values.auth.service.protocol }}"
  ISOL_AUTH_SERVICE_HOST: "{{ .Values.auth.service.name }}"
  ISOL_AUTH_SERVICE_PORT: "{{ .Values.auth.service.port }}"
  ISOL_AUTH_SERVICE_PATH: "{{ .Values.auth.service.path }}"
  ISOL_AUTH_SERVICE_REALM: "{{ .Values.auth.realm }}"
  ISOL_AUTH_SERVICE_API_CLIENT: "{{ .Values.auth.apiClient}}"
  ISOL_AUTH_SERVICE_API_URL: "{{ .Values.external.protocol }}://{{ .Values.external.host }}:{{ .Values.external.port }}{{ .Values.auth.external.path }}"
  ISOL_AUTH_SERVICE_UI_CLIENT: "{{ .Values.auth.uiClient }}"
  ISOL_AUTH_SERVICE_UI_URL: "{{ .Values.external.protocol }}://{{ .Values.external.host }}{{ .Values.discoverUi.external.path }}*"
  ISOL_AUTH_SERVICE_TOKEN_EXPIRY_TIME: "{{ .Values.auth.tokenExpiryTimeSeconds }}"
  ISOL_AUTH_SERVICE_BASE_REALM_ROLES: "{{ .Values.auth.baseRealmRoles }}"

  ISOL_ENTITY_STORAGEDB_HOST: "{{ .Values.entity.storage.service.name }}"
  ISOL_ENTITY_STORAGEDB_PORT: "{{ .Values.entity.storage.service.port }}"
  ISOL_ENTITY_INDEXDB_HOST: "{{ .Values.entity.index.service.name }}"
  ISOL_ENTITY_INDEXDB_ACI_PORT: "{{ .Values.entity.index.service.queryPort }}"
  ISOL_ENTITY_INDEXDB_INDEX_PORT: "{{ .Values.entity.index.service.indexPort }}"
  ISOL_ENTITY_DATA_VOLUME_PATH: "/data/entity"
  ISOL_ENTITY_GRAPH_NAME: "{{ .Values.entity.graphName }}"

  ISOL_AUDIT_HOST: "{{ .Values.audit.service.name }}"
  ISOL_AUDIT_PORT: "{{ .Values.audit.service.port }}"
  ISOL_AUDIT_DATABASE_NAME: "{{ .Values.audit.database }}"

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.initTool.secret }}
data:
  ISOL_AUTH_SERVICE_ADMIN_USER: "{{ .Values.auth.adminUser | b64enc }}"
  ISOL_AUTH_SERVICE_ADMIN_PASS: "{{ .Values.auth.adminPassword | b64enc }}"
  ISOL_AUTH_SERVICE_API_CLIENT_SECRET: "{{ .Values.auth.apiClientSecret | b64enc }}"
  ISOL_AUDIT_USERNAME: "{{ .Values.audit.username | b64enc }}"
  ISOL_AUDIT_PASSWORD: "{{ .Values.audit.password | b64enc }}"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.initTool.filesConfig.configName }}
data:
  entitySchema: |-
{{ .Files.Get "entity-schema.yaml" | indent 4 }}
