#
# Copyright 2021-2023 Open Text.
#
# Licensed under the MIT License (the "License"); you may not use this file
# except in compliance with the License.
#
# The only warranties for products and services of Open Text and its affiliates
# and licensors ("Open Text") are as may be set forth in the express warranty
# statements accompanying such products and services. Nothing herein should be
# construed as constituting an additional warranty. Open Text shall not be
# liable for technical or editorial errors or omissions contained herein. The
# information contained herein is subject to change without notice.
#

services:

  init-tool:
    image: ${ISOL_DOCKER_REGISTRY}${ISOL_DOCKER_NAME_SEP}solutions-init-tool${ISOL_DOCKER_VERSION_SEP}${ISOL_API_VERSION}
    networks:
      - main
    volumes:
      - entity-data:/data/entity
    environment:
      - ISOL_AUTH_SERVICE_PROTOCOL=${ISOL_AUTH_SERVICE_PROTOCOL}
      - ISOL_AUTH_SERVICE_HOST=${ISOL_AUTH_SERVICE_HOST}
      - ISOL_AUTH_SERVICE_PORT=${ISOL_AUTH_SERVICE_PORT}
      - ISOL_AUTH_SERVICE_PATH=${ISOL_AUTH_SERVICE_PATH}
      - ISOL_AUTH_SERVICE_ADMIN_USER=${ISOL_AUTH_SERVICE_ADMIN_USERNAME}
      - ISOL_AUTH_SERVICE_ADMIN_PASS=${ISOL_AUTH_SERVICE_ADMIN_PASSWORD}
      - ISOL_AUTH_SERVICE_REALM=${ISOL_AUTH_SERVICE_REALM}
      - ISOL_AUTH_SERVICE_API_CLIENT=${ISOL_AUTH_SERVICE_API_CLIENT}
      - ISOL_AUTH_SERVICE_API_CLIENT_SECRET=${ISOL_AUTH_SERVICE_API_CLIENT_SECRET}
      - ISOL_AUTH_SERVICE_API_URL=${ISOL_EXTERNAL_PROTOCOL}://${ISOL_API_SERVICE_EXTERNAL_HOST}:${ISOL_API_SERVICE_EXTERNAL_PORT}${ISOL_API_SERVICE_EXTERNAL_PATH}
      - ISOL_AUTH_SERVICE_UI_CLIENT=${ISOL_AUTH_SERVICE_UI_CLIENT}
      - ISOL_AUTH_SERVICE_UI_URL=${ISOL_EXTERNAL_PROTOCOL}://${DISCOVER_UI_EXTERNAL_HOST}:${DISCOVER_UI_EXTERNAL_PORT}${DISCOVER_UI_EXTERNAL_PATH}*,${ISOL_AUTH_SERVICE_ADDITIONAL_UI_URLS}
      - ISOL_AUTH_SERVICE_TOKEN_EXPIRY_TIME=${ISOL_AUTH_SERVICE_TOKEN_EXPIRY_TIME}
      - ISOL_AUTH_SERVICE_BASE_REALM_ROLES=${ISOL_AUTH_SERVICE_BASE_REALM_ROLES}
      - ISOL_ENTITY_STORAGEDB_HOST=${ISOL_ENTITY_STORAGEDB_HOST}
      - ISOL_ENTITY_STORAGEDB_PORT=${ISOL_ENTITY_STORAGEDB_PORT}
      - ISOL_ENTITY_INDEXDB_HOST=${ISOL_ENTITY_INDEXDB_HOST}
      - ISOL_ENTITY_INDEXDB_ACI_PORT=${ISOL_ENTITY_INDEXDB_ACI_PORT}
      - ISOL_ENTITY_INDEXDB_INDEX_PORT=${ISOL_ENTITY_INDEXDB_INDEX_PORT}
      - ISOL_ENTITY_DATA_VOLUME_PATH=/data/entity
      - ISOL_ENTITY_GRAPH_NAME=entities
      - ISOL_AUDIT_HOST=${ISOL_AUDIT_DB_HOST}
      - ISOL_AUDIT_PORT=${ISOL_AUDIT_DB_PORT}
      - ISOL_AUDIT_USERNAME=${ISOL_AUDIT_DB_USERNAME}
      - ISOL_AUDIT_PASSWORD=${ISOL_AUDIT_DB_PASSWORD}
      - ISOL_AUDIT_DATABASE_NAME=${ISOL_AUDIT_DB_NAME}

volumes:
  entity-data:
