#
# Copyright 2021-2024 Open Text.
#
# Licensed under the MIT License (the "License"); you may not use this file
# except in compliance with the License.
#
# The only warranties for products and services of Open Text and its affiliates
# and licensors ("Open Text") are as may be set forth in the express warranty
# statements accompanying such products and services. Nothing herein should be
# construed as constituting an additional warranty. Open Text shall not be
# liable for technical or editorial errors or omissions contained herein. The
# information contained herein is subject to change without notice.
#

services:

  data-entity-vector:
    image: ${ISOL_DOCKER_REGISTRY}${ISOL_DOCKER_NAME_SEP}solutions-data-entity-vector${ISOL_DOCKER_VERSION_SEP}${ISOL_API_VERSION}
    # create a container but don't do anything, so the container is available to list to discover all required images
    entrypoint: "true"
    networks:
      - main

  data-entity-vector-custom:
    image: ${ISOL_DOCKER_REGISTRY}${ISOL_DOCKER_NAME_SEP}solutions-data-entity-vector-custom${ISOL_DOCKER_VERSION_SEP}${ISOL_API_VERSION}
    build:
      context: ../custom/data-entity-vector
      args:
        BASE_IMAGE: ${ISOL_DOCKER_REGISTRY}${ISOL_DOCKER_NAME_SEP}solutions-data-entity-vector${ISOL_DOCKER_VERSION_SEP}${ISOL_API_VERSION}
    networks:
      - main
    volumes:
      - entity-vector-data:/target-volume

volumes:
  entity-vector-data:
