#
# Copyright 2021-2023 Open Text.
#
# Licensed under the MIT License (the "License"); you may not use this file
# except in compliance with the License.
#
# The only warranties for products and services of Open Text and its affiliates
# and licensors ("Open Text") are as may be set forth in the express warranty
# statements accompanying such products and services. Nothing herein should be
# construed as constituting an additional warranty. Open Text shall not be
# liable for technical or editorial errors or omissions contained herein. The
# information contained herein is subject to change without notice.
#

services:

  analysis-live-mediaserver:
    image: ${ISOL_DOCKER_REGISTRY}${ISOL_DOCKER_NAME_SEP}solutions-analysis-live-mediaserver${ISOL_DOCKER_VERSION_SEP}${ISOL_BASE_VERSION}
    networks:
      - main
    volumes:
      - security-data:/data/security
      - entity-data:/data/entity
      - analysis-live-mediaserver-license-data:/mediaserver/license-cache
      - analysis-live-mediaserver-output:/mediaserver/output
    ports:
      - ${ISOL_ANALYSIS_LIVE_MEDIASERVER_ACI_DOCKER_PORT}:14000
    mac_address: 06-00-00-50-00-01
    environment:
      - ISOL_LICENSE_SERVER_HOST=${ISOL_LICENSE_SERVER_HOST}
      - ISOL_LICENSE_SERVER_PORT=${ISOL_LICENSE_SERVER_PORT}

  analysis-live-processor:
    image: ${ISOL_DOCKER_REGISTRY}${ISOL_DOCKER_NAME_SEP}solutions-analysis-live-processor${ISOL_DOCKER_VERSION_SEP}${ISOL_ANALYSIS_LIVE_VERSION}
    networks:
      - main
    volumes:
      - analysis-live-mediaserver-output:/mediaserver-output
      - entity-data:/data/entity
    environment:
      - ISOL_SECURITY_DATA_VOLUME_PATH=/data/security
      - ISOL_ENTITY_STORAGEDB_HOST=${ISOL_ENTITY_STORAGEDB_HOST}
      - ISOL_ENTITY_STORAGEDB_PORT=${ISOL_ENTITY_STORAGEDB_PORT}
      - ISOL_ENTITY_INDEXDB_PROTOCOL=${ISOL_ENTITY_INDEXDB_PROTOCOL}
      - ISOL_ENTITY_INDEXDB_HOST=${ISOL_ENTITY_INDEXDB_HOST}
      - ISOL_ENTITY_INDEXDB_ACI_PORT=${ISOL_ENTITY_INDEXDB_ACI_PORT}
      - ISOL_ENTITY_INDEXDB_INDEX_HOST=${ISOL_ENTITY_INDEXDB_INDEX_HOST}
      - ISOL_ENTITY_INDEXDB_INDEX_PORT=${ISOL_ENTITY_INDEXDB_INDEX_PORT}
      - ISOL_ENTITY_INDEXDB_COMMUNITY_PROTOCOL=${ISOL_ENTITY_INDEXDB_COMMUNITY_PROTOCOL}
      - ISOL_ENTITY_INDEXDB_COMMUNITY_HOST=${ISOL_ENTITY_INDEXDB_COMMUNITY_HOST}
      - ISOL_ENTITY_INDEXDB_COMMUNITY_ACI_PORT=${ISOL_ENTITY_INDEXDB_COMMUNITY_ACI_PORT}
      - ISOL_ENTITY_DATA_VOLUME_PATH=/data/entity
      - ISOL_AUDIT_HOST=${ISOL_AUDIT_DB_HOST}
      - ISOL_AUDIT_PORT=${ISOL_AUDIT_DB_PORT}
      - ISOL_AUDIT_USERNAME=${ISOL_AUDIT_DB_USERNAME}
      - ISOL_AUDIT_PASSWORD=${ISOL_AUDIT_DB_PASSWORD}
      - ISOL_AUDIT_DATABASE_NAME=${ISOL_AUDIT_DB_NAME}
      - ISOL_ANALYSIS_LIVE_MEDIASERVER_HOST=analysis-live-mediaserver
      - ISOL_ANALYSIS_LIVE_MEDIASERVER_ACI_PORT=14000

volumes:
  security-data:
  entity-data:
  analysis-live-mediaserver-license-data:
  analysis-live-mediaserver-output:
