apiVersion: v2
name: discover
description: A Basic IDOL Discover deployment
type: application
version: 0.1.0
appVersion: "24.2.0"
dependencies:
  - name: discover-auth
    alias: auth
    version: 0.1.0
    #repository: file://../discover-auth
    repository: https://raw.githubusercontent.com/opentext-idol/discover-deploy/develop/helm
