licenseServer:
  ip: "REQUIRED"
external:
  host: 192.168.49.2
secret:
  base64dockerconfigjson: "REQUIRED"
docker:
  registry:
    root: "REQUIRED"
    nameSeparator: ":"
    versionSeparator: "-"
  customRegistry:
    root: "192.168.49.1:5000/microfocusidolserver"
  versions:
    base: 24.3.0-SNAPSHOT
    api: 24.3.0-SNAPSHOT
    datasets: 24.3.0-SNAPSHOT
    analysis: 24.3.0-SNAPSHOT
    discoverData: 24.3.0-SNAPSHOT
    discoverApi: 24.3.0-SNAPSHOT
    discover: 24.3.0-SNAPSHOT

dataSecurity:
  customImage: false
entity:
  storage:
    maxHeapSize: 500M
    heapNewSize: 100M
filestore:
  dataVolumeSize: 10Gi
analysis:
  customImage: false
  concurrency:
    threads:
      face: 2
      vehicle: 2
      object: 2
datasets:
  locations:
    replicas: 1
discoverUi:
  replicas: 1
