licenseServer:
  service:
    name: license-service
    port: 20000
  ip: 127.0.0.1
  port: 20000

external:
  protocol: http
  host: localhost
  port: 80

secret:
  name: docker-secret
  base64dockerconfigjson:

docker:
  registry: "microfocusidolserver"
  nameSeparator: "/"
  versionSeparator: ":"
  pullPolicy: IfNotPresent
  versions:
    base: 24.2.0
    api: 24.2.0
    datasets: 24.2.0
    analysis: 24.2.0
    discoverData: 24.2.0
    discover: 24.2.0
    postgres: 16.1

auth:
  enabled: true
  name: auth
  replicas: 1
  container: auth-container
  image: solutions-auth-service
  config: auth-config
  secret: auth-secret
  adminUser: discover-auth
  adminPassword: discover-auth
  realm: discover
  createAdminUsername: admin
  createAdminPassword: admin
  apiClient: discover_api
  apiClientSecret: d0e76ad7-7d6b-4d86-be3a-5dfe715dbf87
  uiClient: discover_ui
  tokenExpiryTimeSeconds: 600
  baseRealmRoles: user
  external:
    # must end with /
    path: /auth/
    adminPort: 30020
  service:
    name: auth-service
    port: 8080
    protocol: http
    path: /
  db:
    config: auth-db-config
    container: auth-service-db
    username: discover
    password: discover
    database: discover-auth
    dataVolume: auth-db-data
    dataVolumeClaim: auth-db-data
    dataVolumeSize: 1Gi

entity:
  graphName: entities
  storage:
    enabled: true
    name: entity-storage-db
    replicas: 1
    container: entity-storage-db-container
    image: solutions-entity-storagedb
    config: entity-storage-db-config
    dataVolume: entity-storage-db-data
    dataVolumeClaim: entity-storage-db-data
    dataVolumeSize: 5Gi
    maxHeapSize: 2G
    heapNewSize: 500M
    service:
      name: entity-storage-db-service
      port: 9042
  index:
    enabled: true
    name: entity-index-db
    replicas: 1
    container: entity-index-db-container
    image: solutions-entity-indexdb
    config: entity-index-db-config
    dataVolume: entity-index-db-data
    dataVolumeClaim: entity-index-db-data
    dataVolumeSize: 5Gi
    service:
      name: entity-index-db-service
      queryPort: 9100
      indexPort: 9101
    ingress:
      enabled: false
      path: /content/

filestore:
  name: filestore
  container: filestore-container
  image: solutions-filestore-service
  secret: filestore-config
  replicas: 1
  enabled: true
  dataVolume: filestore-data
  dataVolumeClaim: filestore-data
  dataVolumeSize: 1Ti
  username: discover-filestore
  password: discover-filestore
  bucket: discover-filestore
  service:
    protocol: http
    name: filestore-service
    port: 8333
    path: /

analysis:
  enabled: true
  name: analysis-nifi
  container: analysis-nifi-container
  image: solutions-analysis-service
  config: analysis-nifi-config
  secret: analysis-nifi-secret
  replicas: 1
  concurrency:
    max: 10
    threads:
      face: 4
      vehicle: 4
      object: 4
    taskCount:
      # Configure the number of tasks that can be concurrently scheduled by each NiFi processor
      createPreview: 4
      extractMetadata: 4
      faceDetection: 4
      faceRecognition: 4
      faceTraining: 4
      fetchS3Object: 4
      imageExtract: 4
      keyViewExportToHTML: 4
      objectClassRecognition: 4
      putIsol: 4
      removeDocumentPart: 4
      transcodeVideo: 4
      vehicleAnalysis: 4
      videoClip: 4
      # The following tasks are internal and should normally be left at the default of 1
      analysisRouteOnAttribute: 1
      createPreviewRouteOnAttribute: 1
      extractJobAttributes: 1
      extractJobOptions: 1
      failIsol: 1
      getLicense: 1
      handleHTTPRequest: 1
      handleHTTPResponseFailure: 1
      handleHTTPResponseSuccess: 1
      htmlFromDocumentRouteOnAttribute: 1
      setContent: 1
  service:
    name: analysis-service
    port: 8090
    jobsPort: 8091
    path: /
    jobsPath: /
  ingress:
    enabled: true
    path: /nifi/

audit:
  enabled: true
  name: audit
  replicas: 1
  container: audit-db
  image: solutions-audit-db
  config: audit-config
  secret: audit-secret
  dataVolume: audit-db-data
  dataVolumeClaim: audit-db-data
  dataVolumeSize: 1Gi
  username: audit-user
  password: audit-pass
  database: audit-db
  service:
    name: audit-service
    port: 5432

datasets:
  locations:
    enabled: true
    name: dataset-locations-db
    replicas: 2
    container: dataset-locations-db-container
    image: solutions-dataset-locations
    config: dataset-locations-db-config
    service:
      name: dataset-locations-db-service
      queryPort: 9100
    ingress:
      enabled: false
      path: /datasets/locations/db/

api:
  enabled: true
  name: api
  replicas: 1
  container: api-container
  internalPort: 8080
  image: solutions-discover-api-service
  config: api-config
  secret: api-secret
  filesConfig:
    configName: api-config-files
    volumeName: api-config-files
  applicationType: discover
  apiEnabled: true
  initEnabled: true
  scheduleEnabled: true
  external:
    path: /api/
  expiry:
    poleLifetimeDays: 365
    caseLifetimeDays: 365
  maxResults:
    max: 10000
    default: 500
    suggestDefault: 500
  idolSecurity:
    mode: denyAll
    aclFormat: "<E=B!>:U:<U=SLE+>:G:<G=SLE+>:NU:<NU=SLE->:NG:<NG=SLE->"
    aclCheck: "NU=[DU]?F:-,NG=[DG]?F:-,E=1?P:-,U=[DU]?P:-,G=[DG]?P:F"
  watchlists:
    minEventAgeSeconds: 60
  stats:
    minAnalysisJobAgeSeconds: 60
  logging:
    apiLogLevel: INFO
    auditLogLevel: WARN
  service:
    name: api-service
    port: 8080

dataEntity:
  name: data-entity
  container: data-entity
  image: solutions-discover-data-entity
  volume: system-entity-data
  volumeClaim: system-entity-data
  volumeSize: 100M

discoverUi:
  enabled: true
  name: discover-ui
  replicas: 2
  container: discover-ui-container
  image: discover-ui
  config: discover-ui-config
  service:
    name: discover-ui-service
    port: 80
  external:
    path: /discover/
