secret:
  # Authentication to pull the IDOL container images from Docker Hub
  base64dockerconfigjson:

# External IDOL License Server that will provide licensing for the system
licenseServer:
  ip:
  port: 20000

# The address of the server running Kubernetes
external:
  host: &external-host localhost
  port: &external-port 80

# Keycloak authentication server
auth:
  # Whether to deploy the component
  enabled: true

  external:
    host: *external-host
    port: *external-port
  
# Storage for application data
entity:
  # IDOL Content database backend
  index:
    # Whether to deploy the component
    enabled: true
    # Maximum database size
    dataVolumeSize: 5Gi
  # Cassandra-compatible database backend
  storage:
    # Whether to deploy the component
    enabled: true
    # Maximum database size
    dataVolumeSize: 5Gi
    # Memory tuning - refer to Cassandra documentation
    maxHeapSize: 2G
    heapNewSize: 500M

# Amazon S3-compatible object storage for files
filestore:
  # Whether to deploy the component
  enabled: true
  # Maximum size for file storage
  dataVolumeSize: 1Ti
  # Credentials to configure and use for access
  username: discover-filestore
  password: discover-filestore
  # Bucket to use for storing files
  bucket: discover-filestore

# Media analysis system
analysis:
  # Whether to deploy the component
  enabled: true
  # Number of analysis processes to run in parallel for each analysis type
  concurrency:
    max: 10
    threads:
      face: 4
      vehicle: 4
      object: 4
    taskCount:
      # Configure the number of tasks that can be concurrently scheduled by each NiFi processor
      createPreview: 4
      extractMetadata: 4
      faceDetection: 4
      faceRecognition: 4
      faceTraining: 4
      fetchS3Object: 4
      imageExtract: 4
      keyViewExportToHTML: 4
      objectClassRecognition: 4
      putIsol: 4
      removeDocumentPart: 4
      transcodeVideo: 4
      vehicleAnalysis: 4
      videoClip: 4

# PostgreSQL database server storing audit logs
audit:
  # Whether to deploy the component
  enabled: true
  # Maximum database size
  dataVolumeSize: 1Gi
  # Credentials to configure and use for access
  username: audit-user
  password: audit-pass
  # Name of the database
  database: audit-db

datasets:
  # Database of global locations
  locations:
    # Whether to deploy the component
    enabled: true
    # Target number of instances to keep running
    replicas: 2

# User-facing web server
api:
  # Whether to deploy the component
  enabled: true
  external:
    # Path on the Kubernetes server to make the Keycloak API and admin UI accessible from
    path: /api/
  expiry:
    # Default number of days until POLE entities are marked for expiry
    poleLifetimeDays: 365
    # Default number of days until case entities are marked for expiry
    caseLifetimeDays: 365
  maxResults:
    # The maximum number of entity IDs that can be retrieved in a single entity traversal
    max: 10000
    # The default number of entity IDs retrieved in a single entity traversal
    default: 500
    # The default number of entity IDs retrieved in a single suggest traversal
    suggestDefault: 500
  logging:
    # The log level for general api service log messages
    apiLogLevel: INFO
    # The log level for audit related log messages
    auditLogLevel: WARN
  idolSecurity:
    # how access to entities using IDOL document security is managed: community, allowAll, or denyAll
    mode: denyAll
    # when mode is community, these should be set to the corresponding configuration values used in the Community
    # component (SecurityACLFormat, SecurityACLCheck)
    aclFormat: "<E=B!>:U:<U=SLE+>:G:<G=SLE+>:NU:<NU=SLE->:NG:<NG=SLE->"
    aclCheck: "NU=[DU]?F:-,NG=[DG]?F:-,E=1?P:-,U=[DU]?P:-,G=[DG]?P:F"


# Discover user interface
discoverUi:
  # Whether to deploy the component
  enabled: true
  # Target number of instances to keep running
  replicas: 2
  external:
    path: /discover/
