apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.dataEntity.volumeClaim }}
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.dataEntity.volumeSize }}
