apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.dataSecurity.volumeClaim }}
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.dataSecurity.volumeSize }}
