apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.initTool.entityData.volumeClaim }}
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
    - ReadOnlyMany
  resources:
    requests:
      storage: {{ .Values.initTool.entityData.volumeSize }}
