apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.db.config }}
data:
  POSTGRES_USER: "{{ .Values.db.username }}"
  POSTGRES_PASSWORD: "{{ .Values.db.password }}"
  POSTGRES_DB: "{{ .Values.db.database }}"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config }}
data:
  KEYCLOAK_DATABASE_HOST: "localhost"
  KEYCLOAK_DATABASE_SCHEMA: "public"
  KC_HOSTNAME_URL: "{{ .Values.external.protocol }}://{{ .Values.external.host }}:{{ .Values.external.port }}{{ .Values.external.path }}"
  KEYCLOAK_FRONTEND_URL: "{{ .Values.external.protocol }}://{{ .Values.external.host }}:{{ .Values.external.port }}{{ .Values.external.path }}"
  {{- if .Values.external.adminHost }}
  KC_HOSTNAME_ADMIN_URL: "{{ .Values.external.protocol }}://{{ .Values.external.adminHost }}:{{ .Values.external.port }}{{ .Values.external.path }}"
  {{- end }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret }}
data:
  KEYCLOAK_ADMIN_USER: "{{ .Values.adminUser | b64enc }}"
  KEYCLOAK_ADMIN_PASSWORD: "{{ .Values.adminPassword | b64enc }}"
  KEYCLOAK_DATABASE_USER: "{{ .Values.db.username | b64enc }}"
  KEYCLOAK_DATABASE_PASSWORD: "{{ .Values.db.password | b64enc }}"
  KEYCLOAK_DATABASE_NAME: "{{ .Values.db.database | b64enc }}"
