apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: isol-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1$2
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-Host $host;

spec:
  rules:
    - http:
        paths:
          - path: {{ .Values.discoverUi.external.path }}()(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.discoverUi.service.name }}
                port:
                  number: {{ .Values.discoverUi.service.port }}
          - path: {{ .Values.auth.external.path }}(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.auth.service.name }}
                port:
                  number: {{ .Values.auth.service.port }}
          - path: {{ .Values.api.external.path }}()(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.api.service.name }}
                port:
                  number: {{ .Values.api.service.port }}
          {{- if .Values.analysis.ingress.enabled }}
          - path: /nifi-api()(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.analysis.service.name }}
                port:
                  number: {{ .Values.analysis.service.port }}
          - path: {{ .Values.analysis.ingress.path }}(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.analysis.service.name }}
                port:
                  number: {{ .Values.analysis.service.port }}
          {{- end }}
          {{- if .Values.entity.index.ingress.enabled }}
          - path: {{ .Values.entity.index.ingress.path }}(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.entity.index.service.name }}
                port:
                  number: {{ .Values.entity.index.service.queryPort }}
          {{- end }}
