apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: isol-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-Host $host;

spec:
  rules:
    - host: {{ .Values.external.host | quote }}
      http:
        paths:
          - path: {{ .Values.discoverUi.external.path }}(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.discoverUi.service.name }}
                port:
                  number: {{ .Values.discoverUi.service.port }}
          - path: {{ .Values.api.external.path }}(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.api.service.name }}
                port:
                  number: {{ .Values.api.service.port }}
